export const cartActionType = {
  ADD_TO_CART: 'ADD_TO_CART',
  REMOVE_FROM_CART: 'REMOVE_FROM_CART',
  SAVE_SHIPPING_ADDRESS: 'SAVE_SHIPPING_ADDRESS',
  SAVE_PAYMENT_METHOD: 'SAVE_PAYMENT_METHOD',
  CLEAR_CART: 'CLEAR_CART',
};
