export const orderActionType = {
  ADD_ORDER_REQUEST: 'ADD_ORDER_REQUEST',
  ADD_ORDER_SUCCESS: 'ADD_ORDER_SUCCESS',
  ADD_ORDER_ERROR: 'ADD_ORDER_ERROR',
  ORDER_DETAIL_REQUEST: 'ORDER_DETAIL_REQUEST',
  ORDER_DETAIL_SUCCESS: 'ORDER_DETAIL_SUCCESS',
  ORDER_DETAIL_ERROR: 'ORDER_DETAIL_ERROR',
  ORDER_LIST_REQUEST: 'ORDER_LIST_REQUEST',
  ORDER_LIST_SUCCESS: 'ORDER_LIST_SUCCESS',
  ORDER_LIST_ERROR: 'ORDER_LIST_ERROR',
};
