export const orderActionType = {
  ADD_ORDER_REQUEST: 'ADD_ORDER_REQUEST',
  ADD_ORDER_SUCCESS: 'ADD_ORDER_SUCCESS',
  ADD_ORDER_ERROR: 'ADD_ORDER_ERROR',
  ORDER_DETAIL_REQUEST: 'ORDER_DETAIL_REQUEST',
  ORDER_DETAIL_SUCCESS: 'ORDER_DETAIL_SUCCESS',
  ORDER_DETAIL_ERROR: 'ORDER_DETAIL_ERROR',
  ORDER_PAY_REQUEST: 'ORDER_PAY_REQUEST',
  ORDER_PAY_SUCCESS: 'ORDER_PAY_SUCCESS',
  ORDER_PAY_ERROR: 'ORDER_PAY_ERROR',
  ORDER_PAY_RESET: 'ORDER_PAY_RESET',
};
