const productActionType = {
  GET_ALL_PRODUCT_REQUEST: 'GET_ALL_PRODUCT_REQUEST',
  GET_ALL_PRODUCT_SUCCESS: 'GET_ALL_PRODUCT_SUCCESS',
  GET_ALL_PRODUCT_FAIL: 'GET_ALL_PRODUCT_FAIL',
  GET_PRODUCT_DETAIL_REQUEST: 'GET_PRODUCT_DETAIL_REQUEST',
  GET_PRODUCT_DETAIL_SUCCESS: 'GET_PRODUCT_DETAIL_SUCCESS',
  GET_PRODUCT_DETAIL_FAIL: 'GET_PRODUCT_DETAIL_FAIL',
  UPDATE_PRODUCT_REQUEST: 'UPDATE_PRODUCT_REQUEST',
  UPDATE_PRODUCT_SUCCESS: 'UPDATE_PRODUCT_SUCCESS',
  UPDATE_PRODUCT_ERROR: 'UPDATE_PRODUCT_ERROR',
  UPDATE_PRODUCT_RESET: 'UPDATE_PRODUCT_RESET',
};
export default productActionType;
